### ISSUE TITLE
Redirect solutions to exercise

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/serlo.org-cloudflare-worker#123]
Only viewing a solution is not very useful, but instead we can redirect to the exercise. The frontend is already just loading the exercise instead of the solution, but this can lead to duplicated content for search engines. The cf worker can make a redirection here (similiar to course -> course page).

**Comment by kulla** [comment]
@Ilaria-F Would you like to implement this? You need to change the function https://github.com/serlo/serlo.org-cloudflare-worker/blob/master/src/utils/index.tsx#L79-L82 You need to change the query so that for solutions also the alias of the exercise is queried. It is similar to the redirect course -> course page as Entkenntnis mentioned. The query https://github.com/serlo/serlo.org-cloudflare-worker/blob/master/src/utils/index.tsx#L114-L118 requests the alias of all course pages and at https://github.com/serlo/serlo.org-cloudflare-worker/blob/master/src/utils/index.tsx#L144-L146 the alias is set to the current course page for pages. Would you like to do this?
