### ISSUE TITLE
frontend-proxy: use unique identifier for cookie name

### ISSUE THREAD

**Issue by inyono** [serlo/serlo.org-cloudflare-worker#15]
Currently, we always use `useFrontend` as the cookie name. This won't have the correct behavior when we update the probability, though (since the old value is still used). We should add an experiment number to the cookie name instead, e.g. `use-frontend-1` which we increment when we change the test so that users receive a new cookie value.

**Comment by kulla** [comment]
It depends. With updating the probability there is no need to update the cookie, it is only necessary when we want to start a new experiment or when we want to change the logic. Let's say we have a probability of 30% and users with the following cookies:

```
User 1: useFrontend=0.25
User 2: useFrontend=0.5
User 3: useFrontend=0.75
```

In this case only the first user sees the new design. After updating the probability to for example 60% there is no need to recalculate the numbers. The first user still gets the new design and now the second user will see it too. Not changing the cookie name in this case has the advantage that the user experience doesn't vary very much, since for only a part of the users the backend changes. We only need to change the cookie, when we want a recalculation of the number for all users. I would suggest that we implement this logic when we really need it.

**Comment by inyono** [comment]
Somehow thought that the value is dependent on the probability, nevermind :)
