### ISSUE TITLE
Thumbnail: Set caching or change implementation

### ISSUE THREAD

**Issue by kulla** [serlo/serlo.org-cloudflare-worker#213]
Follow up of https://github.com/serlo/serlo.org-cloudflare-worker/pull/212: What is a good way to cache the thumbnails? This should be implemented... See also https://developers.cloudflare.com/workers/examples/cache-using-fetch

**Comment by elbotho** [comment]
wikimedia answered with status code 429 (no retry-after header set)

**Comment by elbotho** [comment]
**cf cache**
[By default](https://developers.cloudflare.com/workers/runtime-apis/request#requestinitcfproperties) `cacheTtl` adopts the settings of the server providing the content. All other providers return `Cache-Control` headers with a `max-age` setting that they consider reasonable.
So I would not change this behaviour at this point.

**cache header to browser**
By default cf returns the thumbnails to the clients with a `max-age` setting of a day.
 I think this setting is reasonable and we should only increase it if we run into problems.
 
**fetchWithCache helper**
There already is a `fetchWithCache` function in utils that we can build upon if necessary.
But since we only need a special setting for Wikimedia this should be fine.
