### ISSUE TITLE
Point cloudflare-worker to specific preview deployment

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/serlo.org-cloudflare-worker#24]
Sometimes, we want to test the integration of a preview deployment with de.serlo.org (or serlo-staging.dev). For this case, it would be useful to set the frontend url manually, e.g. by using a cookie.

**Comment by inyono** [comment]
Yep, I have that on my list but didn't get to it yet.

**Comment by inyono** [comment]
This won't work in this direction: we decided that Vercel deployments are fixed to a specific API URL so that we don't need a server request. So if we need this, we need to implement this on frontend side (i.e. tell via config or something to deploy something in a specific environment). Problem might be: AFAIK Vercel accepts only one production deployment, so we probably need to handle that in preview environment.

**Comment by Entkenntnis** [comment]
preview environment would be fine, too

**Comment by Entkenntnis** [comment]
let's say, we want to preview https://frontend-git-client-side-routing.serlo.now.sh in "real production", which means using the cloudflare-worker under de.serlo.org:

I would change set a cookie with the new url and use it here instead:
https://github.com/serlo/serlo.org-cloudflare-worker/blob/99f7730197bca3e46091830df8b26fadcc8d19da/src/frontend-proxy.ts#L75

Optionally we can also point the endpoint to staging if this cookie is set:
https://github.com/serlo/serlo.org-cloudflare-worker/blob/99f7730197bca3e46091830df8b26fadcc8d19da/src/frontend-proxy.ts#L90

This way, when I access de.serlo.org, I can preview the changing in this PR pretty much under live conditions (which would be awesome).

@inyono, @kulla: Does this sounds feasable?

**Comment by inyono** [comment]
That covers only one direction. Basically:
- When you want to test the integration of a preview deployment trough the Cloudflare Worker (e.g. to test if the proxy / other stuff handled in the Worker works as expected), we need a cookie at Cloudflare Worker level (similarly to what you described). But: from frontend side, the deployment is still tied to a specific environment (production or staging) at build-time (because of caching & optimization reasons). Hence:
- To test a preview deployment with the production API, we need a way for the frontend to tell Vercel that they want to get build with the production API stuff (e.g. by setting a constant value `useProduction` that is false by default). This is more common case, I assume.

And to use both, e.g. to test a preview deployment with production API & Cloudflare Worker, we'd need both.

**Comment by kulla** [comment]
At https://github.com/serlo/serlo.org-cloudflare-worker/pull/27 I have started to implement the first direction...

**Comment by inyono** [comment]
First direction is live, second is on my list.

**Comment by inyono** [comment]
Second direction also works (by setting `NEXT_PUBLIC_ENV` to `production` in `.env.production`), see https://github.com/serlo/frontend/pull/331
